/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * [./src/constants/constants.src]{@link ./src/constants/constants.src}
 * 
 **/


export const PATH_ERRORS  = {
    DATA_DIR_FAILED: "Failed to access application data directory"
};

