/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * [./cjs/lib-utils.cjs]{@link ./cjs/lib-utils.cjs}
 * 
 **/
import {PATH_ERRORS}  from "./cjs/constants/constants.mjs";
/**
 *
 */

// ==================================================================
// Built-ins
// ==================================================================


// ==================================================================
// Constants
// ==================================================================

export function  sleep (ms)
{
    return new Promise((resolve) =>
    {
        setTimeout(resolve, ms);
    });
}


/**
 * Simple object check
 * @param item
 * @returns {boolean}
 */
export function  isObject (item)
{
    // null is an object
    if (!item)
    {
        return false;
    }
    // Arrays are objects
    else if (Array.isArray(item))
    {
        return false;
    }
    return typeof item === "object";
}

/**
 * Deep merge two objects.
 * @param target
 * @param sources
 * @see https://stackoverflow.com/questions/27936772/how-to-deep-merge-instead-of-shallow-merge
 */
export function  mergeDeep (target, ...sources)
{
    if (!sources.length)
    {
        return target;
    }
    const source = sources.shift();

    if (isObject(target) && isObject(source))
    {
        for (const key in source)
        {
            if (isObject(source[key]))
            {
                if (!target[key])
                {
                    Object.assign(target, {[key]: {}});
                }
                mergeDeep(target[key], source[key]);
            }
            else
            {
                Object.assign(target, {[key]: source[key]});
            }
        }
    }

    return mergeDeep(target, ...sources);
}

/**
 * Generate a random name
 * @param {string} prefix Prefix generated name with given value
 * @param suffix
 * @param size
 * @param replacementChar
 * @return {string}
 */
export function  generateTempName ({prefix = "", suffix = "", size = 16, replacementChar = "_"} = {})
{
    size = size - prefix.length;
    if (size < 0)
    {
        return prefix;
    }
    return prefix +
        crypto.randomBytes(size).toString("base64").replace(/[^\w\d]/g, replacementChar) +
        suffix;
}

/**
 * Convert a session key property into a CLI argument
 * @example
 *
 * convertSessionKeyNameToArg("staticDirs", ["./", "./public"])
 * // ["--dir", "./", "--dir", "./public"]
 *
 * convertSessionKeyNameToArg("silent")
 * // ["--silent"]
 *
 * convertSessionKeyNameToArg("enableapi", false)
 * // ["--disableapi"]
 * convertSessionKeyNameToArg("enableapi", true)
 * // []
 *
 * convertSessionKeyNameToArg("port", 3000)
 * // ["--port", 3000]
 *
 * convertSessionKeyNameToArg("defaultPage", "index.html")
 * // ["--defaultpage", "index.html"]
 *
 * @param key
 * @param value
 * @returns {(string|*)[]|*[]|*}
 */
export const convertSessionKeyNameToArg  = (key, value = undefined) =>
{
    const table = {
        port       : "port",
        protocol   : "protocol",
        timeout    : "timeout",
        host       : "host",
        defaultPage: "defaultpage",
        silent     : () => ["--silent"],
        staticDirs : (inputs) =>
        {
            const arr = [];
            inputs.forEach((input) =>
            {
                arr.push("--dir");
                arr.push(input);
            });
            return arr;
        },
        enableapi  : (input) =>
        {
            if (!input)
            {
                return ["--disableapi"];
            }

            return [];
        }
    };

    let arg = table[key];
    if (!arg)
    {
        return [];
    }

    if (typeof arg === "function")
    {
        return arg(value);
    }

    const option = `--${arg}`;
    return [option, value];
};

/**
 * Convert session properties to CLI array
 * @param session
 * @param argv
 * @param scriptPath
 * @param command
 * @param target
 * @returns {*}
 */
export const convertSessionToArg  = (session, argv, {scriptPath = "", command = "", target = ""} = {}) =>
{
    const argumentsFromSession = argv.slice(0, 1);

    if (scriptPath)
    {
        if (!fs.existsSync(scriptPath))
        {
            throw new Error(`[${scriptPath}] could not be found`);
        }

        argumentsFromSession.push(scriptPath);
    }

    if (command)
    {
        argumentsFromSession.push(command);
        if (target)
        {
            argumentsFromSession.push(target);
        }
    }

    for (const [key, values] of Object.entries(session))
    {
        const res = convertSessionKeyNameToArg(key, values);
        if (!res || !res.length)
        {
            continue;
        }
        argumentsFromSession.push(...res);
    }
    return argumentsFromSession;
};

export const normalisePath  = (filepath, {isForceLinuxFormat = false, uncroot = ""} = {}) =>
{
    filepath = path.normalize(filepath);
    filepath = filepath.replace(/\\/g, "/");
    if (isForceLinuxFormat)
    {
        const arr = filepath.split(":");
        if (arr.length > 1)
        {
            arr[0] = uncroot || arr[0];
            filepath = arr.join("/");
        }
    }
    return filepath;
};

export const normaliseFileName  = (sessionName) =>
{
    try
    {
        if (!sessionName)
        {
            return "";
        }

        sessionName = sessionName.trim().toLowerCase();
        return sessionName;
    }
    catch (e)
    {
        console.error(e);
    }
};

/**
 * Join and optimise path
 * @alias path.join
 * @param args
 * @returns {any}
 */
export const joinPath  = (...args) =>
{
    let filepath = path.join(...args);
    filepath = normalisePath(filepath);
    return filepath;
};

/**
 * Resolve and optimise path (replace backslashes with forward slashes)
 * @alias path.resolve
 * @param filepath
 * @returns {*}
 */
export const resolvePath  = (filepath) =>
{
    filepath = path.resolve(filepath);
    filepath = normalisePath(filepath);
    return filepath;
};

export const isItemInList  = (item, list = []) =>
{
    if (!item)
    {
        return false;
    }

    if (!Array.isArray(list))
    {
        throw new Error("list should be an array");
    }

    if (!list || !list.length)
    {
        return false;
    }
    return list.includes(item);
};

/**
 * Calculate file size
 * @param file
 * @returns {number}
 */
export const getFilesizeInBytes  = (file) =>
{
    const stats = fs.statSync(file);
    return stats.size;
};

export const convertToUrl  = ({protocol, host, port, pathname}) =>
{
    const url = new URL("http://localhost");
    url.protocol = protocol;
    url.host = host;
    url.port = port;
    if (pathname)
    {
        url.pathname = pathname;
    }

    return url.toString();
};

/**
 * Do nothing. Everything you do is to make any linter ignore you.
 * @param args
 */
export const doNothing  = function (args)
{
    if (!args)
    {
        console.log({lid: 2000, target: "void"}, args);
    }
};

/**
 * If source finishes with a "/", it's a folder,
 * otherwise, it's not.
 * @returns {boolean}
 */
const isConventionalFolder = (source) =>
{
    if (!source)
    {
        return false;
    }
    return source.charAt(source.length - 1) === "/";
};

/**
 * Use conventions (See file top)
 * @todo Change function name to more appropriate name
 * @param source
 * @param requiredPath
 * @returns {string}
 */
export const calculateRelativePath  = (source, requiredPath) =>
{
    source = normalisePath(source);
    requiredPath = normalisePath(requiredPath);

    if (!isConventionalFolder(source))
    {
        source = path.parse(source).dir + "/";
    }

    const relativePath = path.relative(source, requiredPath);
    return normalisePath(relativePath);
};


export const fetchSync  = async function (url, isJson = false)
{
    return new Promise(async function (resolve, reject)
    {
        try
        {
            https.get(url, res =>
            {
                let data = "";

                res.on("data", chunk =>
                {
                    data += chunk;
                });

                res.on("end", () =>
                {
                    data = isJson ? JSON.parse(data) : data;
                    resolve(data);
                });

            }).on("error", err =>
            {
                console.log(err.message);
            });
        }
        catch (e)
        {
            reject(e);
        }
    });
};

/**
 *
 * @param number
 * @param type
 */
export function  addPlural (number, type = "word")
{
    if (type === "verb")
    {
        return number === 1 ? "s" : "";
    }
    else if (type === "word")
    {
        return number === 1 ? "" : "s";
    }
}

// ==================================================================
// Path Related functions
// ==================================================================
//
// ------------------------------------------------------------------
/**
 * Returns OS data dir for the application
 * @returns {string|null}
 */
export const getAppDataDir  = (appName) =>
{
    try
    {
        const osDataDir = process.env.APPDATA || (process.platform === "darwin" ? process.env.HOME + "/Library/Preferences" : process.env.HOME + "/.local/share");
        return joinPath(osDataDir, appName);
    }
    catch (e)
    {

    }
    return null;
};

/**
 *
 * @returns {boolean}
 */
export const createAppDataDir  = (appName) =>
{
    try
    {
        const appDataDir = getAppDataDir(appName);
        if (!appDataDir)
        {
            console.error(PATH_ERRORS.DATA_DIR_FAILED);
            return false;
        }

        if (!fs.existsSync(appDataDir))
        {
            fs.mkdirSync(appDataDir, {recursive: true});
        }

        return fs.lstatSync(appDataDir).isDirectory();
    }
    catch (e)
    {
        console.error(e.message);
    }

    return false;
};


// Generic functions



















// Path Related functions

