/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * [./cjs/constants/constants.cjs]{@link ./cjs/constants/constants.cjs}
 * 
 **/


export const PATH_ERRORS  = {
    DATA_DIR_FAILED: "Failed to access application data directory"
};

