name: Test
env:
  ANALOGGER_APP_NAME: "release/libutils"
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**.md"
      - ".vscode/**"
jobs:
  run-test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Check out Git repository
        uses: thimpat/libutils/.github/actions/checkout@ci
      - name: Install dependencies
        shell: powershell
        run: |
          npm ci install
      - name: Generate libutils for Node & browsers
        shell: powershell
        run: |
          npm run build:all
          # The E2E tests need this build
          npm run build:demo
      - name: Test
        shell: powershell
        run: |
          npm run lint
          npm test
