name: Build
env:
  ANALOGGER_APP_NAME: "release/libutils"
on:
  push:
    branches:
      - main
      - ci
    paths-ignore:
      - "**.md"
      - ".vscode/**"
jobs:
  set-version:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Check out Git repository
        uses: thimpat/libutils/.github/actions/checkout@main
      - name: Install dependencies
        shell: powershell
        run: |
          npm ci install
      - name: Generate libutils for Node & browsers
        shell: powershell
        run: |
          npm run build:all
      - name: Test main
        shell: powershell
        run: |
          npm test
